### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by ArdiWeb-Dev** [nstar-y/bail#2]
Bang cara atasi error: const resolvedOption = FSLegacyMainResolve(packageJsonUrlString, packageConfig.main, baseStringified);
                         ^
Error: Cannot find package '/storage/emulated/0/a/node_modules/@whiskeysockets/baileys/package.json' imported from /storage/emulated/0/a/main.js

Gimana? Mohon di Jawab Terima kasih

**Comment by nstar-y** [comment]
coba cek lagi di package script mu, udah bener blom kayak gini

    "dependencies": {
       "@whiskeysockets/baileys": "github:nstar-y/Bail"
    }

atau coba install ulang semua 
`rm -rf node_modules package-lock.json`
`npm install`

**Comment by ArdiWeb-Dev** [comment]
Soalnya saya fork dari punya lu bg tadi lalu saya install malah gitu

**Comment by nstar-y** [comment]
make versi node brpa bang

**Comment by ArdiWeb-Dev** [comment]
v21.6.2

**Comment by ArdiWeb-Dev** [comment]
Coba caraa fork baileys gimana?

**Comment by nstar-y** [comment]
pke versi yg saya kasih tadi aj coba

**Comment by ArdiWeb-Dev** [comment]
Tapi saya mau fork ajarin bg

**Comment by nstar-y** [comment]
tinggal fork aja 

cobain dulu mke versi yg saya kasih, klo masih tetep gabisa berarti memang bermasalah node mu, coba cek [disini](https://github.com/nodejs/node/issues/49674) eror nya sama

**Comment by ArdiWeb-Dev** [comment]
Sama juga
